name: Linux, Windows, macOS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    name: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies for ${{ matrix.os }}
        run: sudo apt-get install -y rhash
        if: matrix.os == 'ubuntu-latest'

      - name: Install dependencies for ${{ matrix.os }}
        run: brew install rhash
        if: matrix.os == 'macos-latest'

      - name: mkdir
        run: mkdir build

      - name: configure
        working-directory: ./build
        run: cmake -DCMAKE_BUILD_TYPE="Debug" ..
        if: matrix.os != 'windows-latest'

      - name: checkout vcpkg
        uses: actions/checkout@v2
        with:
          repository: "microsoft/vcpkg"
          ref: 6ba505cf2c1752d8ea5abb21427e23ff89dc486f
          path: vcpkg
        if: matrix.os == 'windows-latest'

      - name: "Setup vcpkg"
        run: ./vcpkg/bootstrap-vcpkg.bat
        if: matrix.os == 'windows-latest'

      - name: configure (with vcpkg)
        working-directory: ./build
        run: |
          cmake -DCMAKE_TOOLCHAIN_FILE="vcpkg\scripts\buildsystems\vcpkg.cmake" ..
        shell: cmd
        if: matrix.os == 'windows-latest'

      - name: build
        working-directory: ./build
        run: cmake --build .

      - name: test
        working-directory: ./build
        run: ctest -C Debug .
